FROM nginx:latest

WORKDIR /usr/share/nginx/html

COPY web/* .


# RUN apt update; apt-get install git -y

# RUN git clone https://github.com/sarkartanmay393/Portfolio-Web.git

# RUN mv Portfolio-Web/* 